### ISSUE TITLE
Why the mandatory arguments?

### ISSUE THREAD

**Issue by vascowhite** [brightsparklabs/gulp-pandoc-pdf#1]
From the docs:-

> The following command line parameters are automatically passed to pandoc: ['--toc', '--number-sections']

Just wondering why, as pandoc works fine without them. They were not in line with what I wanted in my output, so I edited them out of your code.

I just change line 32 to :-

```
var mandatoryArgs = [];
```

Maybe provide an option to switch them off. Or leave them out altogether as they can be passed in `args` if needed?

Nice useful app by the way :)

**Comment by al-jeyapal** [comment]
Yes you're right, it's not necessary for the published version. It was something used internally as defaults. We'll address it.

**Comment by al-jeyapal** [comment]
Resolved by https://github.com/brightsparklabs/gulp-pandoc-pdf/pull/2
